- pkts-buffers/src/main/java/io/pkts/buffer/Buffers.java
- pkts-buffers/src/main/java/io/pkts/buffer/ByteBuffer.java
- pkts-core/src/main/java/com/google/polo/pairing/HexDump.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1943 Classes and methods that rely on the default system encoding should not be used
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1943
Please let me know if you have any questions.
Zeeshan Asghar
> Classes and methods that rely on the default system encoding should not be used

- pkts-buffers/src/main/java/io/pkts/buffer/ByteNotFoundException.java
- pkts-core/src/main/java/com/google/polo/pairing/HexDump.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:UselessParenthesesCheck Useless parentheses around expressions should be removed to prevent any misunderstanding
findbugs:DMI_INVOKING_TOSTRING_ON_ARRAY Correctness - Invocation of toString on an array
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:UselessParenthesesCheck 
https://dev.eclipse.org/sonar/rules/show/findbugs:DMI_INVOKING_TOSTRING_ON_ARRAY
Please let me know if you have any questions.
Zeeshan Asghar
> General Code Improvement 1

- pkts-sip/src/main/java/io/pkts/packet/sip/address/SipURI.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipUserHostInfo.java
- pkts-sip/src/test/java/io/pkts/packet/sip/impl/SipParserTest.java
Comprehensive rewrite of User Info/Host/Port parsing with robust validation.
As we parse the username/host portion of the URI, we should perform basic validation, especially on the host portion, so we can catch user error early.
* The host portion of the SIP URI is strictly validated against RFC 3261.
- Hostnames and IPv4 addresses are validated to spec.
- **IPv6 is currently not supported (the parser will generate an error), but should be relatively simple to add later.**
* Port numbers are broken out, and checked to ensure they contain at least one digit (acceptable integer range validation could be added later, but is not in the RFC if I recall)
* JUnits were added to test against a variety of malformed SIP URIs
* Functionality in `SipParser.consumeUserInfoHostPort()` has been broken …
> Robust SIP Hostname validation

- pkts-buffers/src/main/java/io/pkts/buffer/AbstractBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/BoundedInputStreamBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/EmptyBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/InputStreamBuffer.java
- pkts-sip/src/main/java/io/pkts/packet/sip/SipMessage.java
- pkts-sip/src/main/java/io/pkts/packet/sip/header/CSeqHeader.java
- pkts-sip/src/main/java/io/pkts/packet/sip/header/SipHeader.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/ImmutableSipMessage.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
This pull request is focused on resolving occurrences of Sonar rule
squid:S1192 String literals should not be duplicated
You can find more information about the issue here:
https://dev.eclipse.org/sonar/rules/show/squid:S1192
Please let me know if you have any questions.
Zeeshan Asghar
> String literals should not be duplicated

- pkts-core/src/main/java/io/pkts/packet/impl/TransportPacketFactoryImpl.java
- pkts-sip/src/main/java/io/pkts/packet/sip/header/impl/ParametersSupport.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1170 Public constants and fields initialized at declaration should be 'static final' rather than merely 'final'
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1170 
Please let me know if you have any questions.
Zeeshan Asghar
> Public constants and fields initialized at declaration should be 'static final' rather than merely 'final'

- pkts-sip/src/main/java/io/pkts/packet/sip/SipParseException.java
- pkts-sip/src/main/java/io/pkts/packet/sip/address/SipURI.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipUserHostInfo.java
- pkts-sip/src/test/java/io/pkts/packet/sip/address/impl/SipUriImplTest.java
- pkts-sip/src/test/java/io/pkts/packet/sip/impl/SipParserTest.java
Several small changes to improve the usefulness of error messages thrown during parsing a SIP URI.
In nearly every case, we are now able to provide a useful index to the character responsible for the error, giving developers and/or end users a meaningful indication of where they went wrong.
Notes:
* SipParseException was modified to take in a format string ("template") that is passed to String.format along with the "count" parameter.  This allows an outer method to re-throw a new exception with the same message but a different index that may be more relevant to the overall URI or SIP message being parsed.  For example, the user/host parser may throw an exception indicating an error on the second character in the user/host portion, but this would be the 6th char in the overall URI.
* …
> User-friendly exception messages when parsing SIP URIs

- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
- pkts-sip/src/test/java/io/pkts/packet/sip/SipRequestTest.java
For SIP packets that are truncated and have their message bodies
cut off before content-length is reached, read what's available
and continue processing rather than throwing an exception.
> Gracefully handles truncated SIP packets

- pkts-buffers/src/main/java/io/pkts/buffer/ByteBuffer.java
- pkts-buffers/src/test/java/io/pkts/buffer/ByteBufferTest.java
- pkts-sip/src/main/java/io/pkts/packet/sip/header/SipHeader.java
- pkts-sip/src/main/java/io/pkts/packet/sip/header/impl/SipHeaderImpl.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
- pkts-sip/src/test/java/io/pkts/packet/sip/header/SipHeaderTest.java
According to the RFC, SIP header names are not case sensitive; this changes the parsing to allow case-insensitive matching. It does not do anything about parsing of header values, which are supposed to be case-insensitive unless inside quotes; I haven't tested that and can't comment on it. I added test support for case-sensitivity in SIP header matching.
It will do some short-lived object creation during the matching process; if you're sensitive to that and would like to keep heap churn lower, I can modify the code, but if it's not important, I think the current implementation is a little clearer.
> Does case-insensitive parsing of SIP headers

- pkts-buffers/src/main/java/io/pkts/buffer/BoundedInputStreamBuffer.java
- pkts-buffers/src/test/java/io/pkts/buffer/BoundedInputStreamBufferTest.java
Found a flaw where reading a second time resulted in empty bytes
> Fix bug in BoundedInputStreamBuffer

- pkts-core/src/main/java/io/pkts/framer/EthernetFramer.java
- pkts-core/src/test/java/io/pkts/framer/EthernetFramerTest.java
I really should support even more EtherTypes here, but we need to implement framer dispatch for IPv4 vs. IPv6 first, anyway.
I'm parsing some pcaps from my own LAN, and if I don't recognize ARP, then parsing the captures errors out.
> Recognize ARP packets as valid Ethernet packets

- pkts-buffers/src/main/java/io/pkts/buffer/BoundedInputStreamBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/InputStreamBuffer.java
- pkts-buffers/src/test/java/io/pkts/buffer/BoundedInputStreamBufferTest.java
- pkts-core/src/main/java/io/pkts/Pcap.java
- Unexpected end-of-stream exception would cause endless loop.
- BoundedInputStreamBuffer had a 2gb limit on PCAP stream. Fixed by changing from 32bit to 64bit indexes.
- BoundedInputStreamBuffer had an incorrect slice function. Code added but commented out as nobody uses these function.
- BoundedInputStreamBuffer had various unimplemented/unused methods, changed them all to throw not-implemented-exceptions.
- BoundedInputStreamBuffer had a cyclic buffer that is smaller than default snaplength in tcpdump, causing errors with packets automatically defragmented by hardware (LRO/GRO).
- Allow clients of Pcap.java to decide on buffer size in BoundedInputStreamBuffer, to match what snaplength was used during capture, as new default is quite large (256kb).
> Fixing issues around continuous streaming of (large) pcap data

- pkts-core/src/main/java/io/pkts/Pcap.java
- pkts-core/src/main/java/io/pkts/framer/EthernetFramer.java
- pkts-core/src/main/java/io/pkts/framer/Framer.java
- pkts-core/src/main/java/io/pkts/framer/FramingException.java
- pkts-core/src/main/java/io/pkts/packet/Packet.java
- pkts-core/src/main/java/io/pkts/packet/impl/AbstractPacket.java
- pkts-core/src/main/java/io/pkts/packet/impl/PCapPacketImpl.java
- pkts-core/src/test/java/io/pkts/framer/PcapFramerTest.java
- pkts-examples/src/main/java/io/pkts/examples/core/CoreExample001.java
- pkts-examples/src/main/java/io/pkts/examples/core/CoreExample002.java
- pkts-examples/src/main/java/io/pkts/examples/streams/StreamsExample001.java
I'm in the process of implementing a tool that needs to be able to seek to arbitrary points in a pcap file in O(1) time, which means I have to depend on the framers to find the next valid packet at a particular point. To that end, I've been adding a bunch of frame validation code, and I wound up adding a new exception type to facilitate checking for framing errors. This patch is just the initial type changes and a teensy bit of validation, so that we can discuss whether this is the right way forward.
I'm looking for feedback on whether this is a good thing and what alternatives might be better. The first thing that comes to mind for me is fleshing out the accept() methods, instead of adding a new exception, but the raw RuntimeException in EthernetFramer made me think this is worthwhile.
> Introduce FramingException for better handling of framing errors

- pkts-core/src/main/java/io/pkts/packet/impl/IPv4PacketImpl.java
- pkts-core/src/test/java/io/pkts/packet/impl/IPv4PacketImplTest.java
Previously it was documented as returning the header length in bytes, but it actually returned the header length in 32-bit words.
> Fix calculation of IPv4 header length

- pkts-core/src/main/java/io/pkts/packet/impl/IPv4PacketImpl.java
- pkts-core/src/main/java/io/pkts/packet/impl/IPv6PacketImpl.java
This enables callers to catch PacketParseException explicitly.
> Throw PacketParseException instead of RuntimeException when IPv4 encounters a next protocol it can't handle

- pkts-core/src/main/java/io/pkts/framer/PcapFramer.java
While I was working on `ChannelBuffer`, I wound up catching a bug during decoding thanks to length being negative. This is a reasonable thing to check in general as a minimal sanity check of a PCAP header.
> Ensure a valid PCAP length before trying to frame it

- pkts-buffers/src/main/java/io/pkts/buffer/BoundedInputStreamBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/Buffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/ByteBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/EmptyBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/InputStreamBuffer.java
The `Buffer#getByes(byte[])` method suffered from a typo. The method has been renamed
and a (deprecated) default implementation with the old name has been added which
delegates to the correctly spelled method, so that existing consumers of the misspelled
method don't break.
> Fix typo in method name `Buffer#getByes(byte[])`

- pkts-buffers/src/main/java/io/pkts/buffer/BaseBuffer.java
- pkts-buffers/src/main/java/io/pkts/buffer/EmptyBuffer.java
- pkts-sip/src/main/java/io/pkts/packet/sip/address/Address.java
- pkts-sip/src/main/java/io/pkts/packet/sip/header/FromHeader.java
- pkts-sip/src/main/java/io/pkts/packet/sip/header/impl/ParametersSupport.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
- pkts-sip/src/test/java/io/pkts/packet/sip/SipRequestTest.java
- pkts-sip/src/test/java/io/pkts/packet/sip/address/impl/AddressImplTest.java
- pkts-sip/src/test/java/io/pkts/packet/sip/address/impl/SipUriImplTest.java
- pkts-sip/src/test/java/io/pkts/packet/sip/header/impl/ParametersSupportTest.java
- pkts-sip/src/test/java/io/pkts/packet/sip/impl/SipParserTest.java
- pkts-sip/src/test/resources/io/pkts/issue-106_001.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_002.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_003.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_004.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_005.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_006.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_007.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_008.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_009.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_010.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_011.txt
- pkts-sip/src/test/resources/io/pkts/issue-106_012.txt
According to specification, a name-addr is not allowed to have any white
space between the host and the parameter list like so:
`<sip:alice@example.com;       wrong=no_space_please>`. However, this does occur
in the "wild" and just "looking" at the address, it is clear that those
parameters should belong to the URI. Therefore, those extra spaces
should really be allowed so the fix is essentially relaxing the rules a
bit.
Then, even if the old rules were more strict, we shouldn't end up in a
loop. It is unclear exactly what the customer who reported the issue ran
into but ultimately, due to the above poor parsing, we ended up with a
ParametersSupport that had "bad values" it couldn't parse and got stuck
in an endless loop.
So, there were several contributing issues (it seems).
1. Poor …
> Fixes 106 - Infinite loop for whitespace in param handling in URI

- pkts-core/src/main/java/io/pkts/packet/sip/impl/SipPacketImpl.java
When parsing large-scale pcap file, I have faced heap memory exception. After investigating problem, I found the bug and fixed it like this.
> updated parseSipContent()

- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
In our production system we caught a pcap that had a `To:` SIP header separated from the `From:` header by `LF` character (0x0A) instead of the usual CRLF (0x0D0A) combination. This caused this library to end up in a sort-of an infinite loop that caused our service's CPU to be pegged, essentially rendering our service useless.
W're not sure `LF` separators are allowed, but in order to fix this issue we decided to update the SipParser to consider `LF` to be a valid separator of SIP headers. This PR shows the changes that we made.
> Update SipParser to allow for LF terminated SIP headers

- pkts-core/src/main/java/io/pkts/Pcap.java
I hope that this fits with the design of the library.
Accessing the global header while processing a stream is required to know whether the captures use microsecond or nanosecond precision. I can also imagine that other use cases might require access to other fields such as the data link type.
> Add getter for the `Pcap` global header

- pkts-core/src/main/java/io/pkts/frame/PcapGlobalHeader.java
- pkts-core/src/test/java/io/pkts/frame/PcapGlobalHeaderTest.java
This makes the PcapGlobalHeader write out nanosecond magic numbers when
appropriate.
The current implementation is incorrect as it writes doesn't take the `nsTimestamps` field into account.
> Support writing nanosecond precision global headers

- pkts-buffers/src/main/java/io/pkts/buffer/Buffers.java
- pkts-buffers/src/main/java/io/pkts/buffer/ByteBuffer.java
- pkts-core/src/main/java/com/google/polo/pairing/HexDump.java
- pkts-core/src/main/java/io/pkts/packet/sip/SipPacket.java
- pkts-core/src/main/java/io/pkts/packet/sip/impl/SipPacketImpl.java
- pkts-sip/src/main/java/io/pkts/packet/sip/SipMessage.java
- pkts-sip/src/main/java/io/pkts/packet/sip/address/Address.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/ImmutableSipMessage.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/ImmutableSipRequest.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/ImmutableSipResponse.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipMessageBuilder.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipMessageStreamBuilder.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipRequestBuilder.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipResponseBuilder.java
- pkts-sip/src/test/java/io/pkts/packet/sip/impl/SipParserTest.java
…alue the SipHeader representation
- Fast access to most common headers is done using reference to header to headers structure
- Improved consumeSWS/consumeLWS by removing handling and returning 0(too many exceptions thrown)
- Use StandardCharsets instead of Charset.forName
> Parsing improvements

- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipParser.java
- pkts-sip/src/main/java/io/pkts/packet/sip/impl/SipUserHostInfo.java
- pkts-sip/src/test/java/io/pkts/packet/sip/impl/SipParserTest.java
* Add IPv6 parser in SipUserHostInfo based on RFC 3261
* Add unit tests for IPv6 address in SIP URI
> Fixes #129 - Support IPv6 address in SIP URI

- pkts-core/pom.xml
- pkts-sdp/pom.xml
- pkts-sip/pom.xml
- pkts-streams/pom.xml
- pom.xml
As there has been non-backwards compatible changes, especially after Java 9, in regards to how Mockito can, and is allowed, to mock things, I was forced to upgrade Mockito, which also forced me to move to Java 11 as the minimum version. If not, it seems that people would be stuck on using Java 8 for this library with very old versions of e.g. mockito.
Java 8, althoug still supported, is way old so let's move forward. Let's face it, Java 11 is also pretty old at this point.
> Java 11 now minimum version, upgrading dependencies.

- pom.xml
An upcoming PR is forcing pkts.io to move to Java 16 (for good reasons), but as I'd rather have an LTS release, I am preemptively forcing the version to Java 17.
> Setting the min Java version to 17
